"""
Alert management and correlation engine.
"""
import json
import time
import logging
from dataclasses import dataclass, asdict
from typing import Dict, List, Optional
from collections import defaultdict

logger = logging.getLogger(__name__)


@dataclass
class Alert:
    """Security alert generated by detection engine."""
    id: str
    timestamp: float
    src_ip: str
    dst_ip: str
    protocol: str
    alert_type: str
    severity: str
    score: float
    description: str
    flow_features: Dict
    raw_data: Optional[Dict] = None


class AlertManager:
    """Manage alert lifecycle: generation, dedup, correlation, storage."""

    def __init__(self, correlation_window: float = 300.0):
        self.correlation_window = correlation_window
        self.alerts: List[Alert] = []
        self.correlation_state: Dict[str, List[Alert]] = defaultdict(list)

    def generate_alert(
        self, src_ip: str, dst_ip: str, protocol: str,
        alert_type: str, severity: str, score: float,
        description: str, flow_features: Dict, raw_data: Optional[Dict] = None,
    ) -> Alert:
        alert = Alert(
            id=f"SS-{int(time.time())}-{len(self.alerts)}",
            timestamp=time.time(),
            src_ip=src_ip,
            dst_ip=dst_ip,
            protocol=protocol,
            alert_type=alert_type,
            severity=severity,
            score=score,
            description=description,
            flow_features=flow_features,
            raw_data=raw_data,
        )
        self.alerts.append(alert)
        self._correlate(alert)
        logger.warning(f"Alert: [{severity}] {alert_type} from {src_ip} to {dst_ip}")
        return alert

    def _correlate(self, alert: Alert):
        """Simple temporal correlation - group alerts by src_ip within window."""
        key = alert.src_ip
        now = time.time()
        self.correlation_state[key].append(alert)
        self.correlation_state[key] = [
            a for a in self.correlation_state[key]
            if now - a.timestamp < self.correlation_window
        ]
        if len(self.correlation_state[key]) >= 5:
            logger.critical(
                f"Correlation: {len(self.correlation_state[key])} alerts from "
                f"{key} in {self.correlation_window}s - possible attack in progress"
            )

    def get_alerts(self, severity: Optional[str] = None, limit: int = 100) -> List[Alert]:
        filtered = self.alerts
        if severity:
            filtered = [a for a in filtered if a.severity == severity]
        return sorted(filtered, key=lambda a: a.timestamp, reverse=True)[:limit]

    def clear(self):
        self.alerts.clear()
        self.correlation_state.clear()

    def export_json(self, path: str):
        with open(path, 'w') as f:
            json.dump([asdict(a) for a in self.alerts], f, indent=2)
        logger.info(f"Exported {len(self.alerts)} alerts to {path}")
